ci/cd action/setup from jdk to java

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,19 +103,23 @@ jobs:
             APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
 
   deploy:
-    name: Delpoy Backend
+    name: Deploy Backend
     runs-on: ubuntu-latest
-    needs: [build-image]
+    needs: [ build-image ]
     steps:
       - name: Create deployment folder
-        run: ssh -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ci-cd"
+        run: |
+          ssh -v -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ci-cd"
+          if [ $? -ne 0 ]; then exit 1; fi  # Check exit code for SSH
 
       - name: Copy docker-compose file
-        run: scp docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:ci-cd/docker-compose.yml
+        run: |
+          scp -v docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:ci-cd/docker-compose.yml
+          if [ $? -ne 0 ]; then exit 1; fi  # Check exit code for SCP
 
       - name: Set ENV variables and deploy
         run: |
-          ssh -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
+          ssh -v -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
           export EMAIL_HOSTNAME=${{ secrets.EMAIL_HOSTNAME }}
           export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
           export EMAIL_USER_PASSWORD=${{ secrets.EMAIL_USER_PASSWORD }}
@@ -123,3 +127,5 @@ jobs:
           docker-compose -f docker-compose.yml pull -q
           docker-compose -f docker-compose.yml up -d
           EOF
+          if [ $? -ne 0 ]; then exit 1; fi  # Check exit code for SSH
+  
