ci/cd debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -103,22 +103,30 @@ jobs:
             APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
 
   deploy:
-    name: Delpoy Backend
+    name: Deploy Backend
     runs-on: ubuntu-latest
-    needs: [build-image]
+    needs: [ build-image ]
     steps:
       - name: Create SSH key file
         run: |
-          echo "${{ secrets.EC2_PRIVATE_KEY }}" > sarafKEY.pem
-          chmod 600 sarafKEY.pem
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > sarafKEY.pem
+          chmod 600 sarafKEY.pem  # Ensure proper permissions for the key
 
-      - name: Create deployment folder
-        run: ssh -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ci-cd"
+      - name: Add EC2 host to known_hosts
+        run: |
+          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
 
-      - name: Copy docker-compose file
-        run: scp docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:ci-cd/docker-compose.yml
+      - name: Create deployment folder on EC2
+        run: |
+          ssh -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "mkdir -p ci-cd"
+          if [ $? -ne 0 ]; then exit 1; fi  # Check SSH exit code
 
-      - name: Set ENV variables and deploy
+      - name: Copy docker-compose file to EC2
+        run: |
+          scp -i sarafKEY.pem docker-compose.yml ec2-user@${{ secrets.EC2_PUBLIC_IP }}:ci-cd/docker-compose.yml
+          if [ $? -ne 0 ]; then exit 1; fi  # Check SCP exit code
+
+      - name: Set environment variables and deploy on EC2
         run: |
           ssh -i sarafKEY.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} <<EOF
           export EMAIL_HOSTNAME=${{ secrets.EMAIL_HOSTNAME }}
@@ -128,3 +136,4 @@ jobs:
           docker-compose -f docker-compose.yml pull -q
           docker-compose -f docker-compose.yml up -d
           EOF
+          if [ $? -ne 0 ]; then exit 1; fi  # Check SSH exit code
